#!/usr/bin/env node
// Helper for action/run.sh. Reads a `rosetta push --json` result.
//   summary.mjs files <result.json>     → paths to stage, one per line
//   summary.mjs markdown <result.json>  → markdown summary for PR bodies / step summary
import { readFileSync } from "node:fs";

const [mode, path] = process.argv.slice(2);
const result = JSON.parse(readFileSync(path, "utf8"));
const locales = result.locales ?? [];

if (mode === "files") {
	const files = new Set();
	for (const locale of locales) if (locale.written) files.add(locale.file);
	if (locales.some((locale) => locale.ok)) files.add(".rosetta/lock.json");
	process.stdout.write([...files].map((f) => `${f}\n`).join(""));
	process.exit(0);
}

if (mode !== "markdown") {
	console.error(`unknown mode: ${mode}`);
	process.exit(2);
}

const fmt = (n) => Number(n ?? 0).toLocaleString("en-US");
const lines = ["### 🌐 Rosetta translations", ""];
const changed = locales.filter((l) => l.written || !l.ok);
if (changed.length === 0) {
	lines.push("All translations are up to date.");
} else {
	lines.push("| Locale | File | Translated | Adopted | Removed | Status |");
	lines.push("| --- | --- | ---: | ---: | ---: | --- |");
	for (const l of changed) {
		lines.push(
			`| \`${l.locale}\` | \`${l.file}\` | ${l.translated} | ${l.adopted} | ${l.removed} | ${l.ok ? "✅ written" : `❌ ${l.errors.length} failed — not written`} |`,
		);
	}
}
const usage = result.usage ?? {};
if (usage.requests) {
	lines.push(
		"",
		`${fmt(usage.requests)} requests · ${fmt(usage.inputTokens)} input / ${fmt(usage.outputTokens)} output tokens`,
	);
}
const failed = locales.filter((l) => !l.ok);
if (failed.length > 0) {
	lines.push("", "<details><summary>Failed keys</summary>", "");
	for (const l of failed) {
		for (const e of l.errors.slice(0, 20)) {
			lines.push(
				`- \`${l.locale}\` \`${e.key || l.file}\` — ${e.rule}: ${e.message}`,
			);
		}
		if (l.errors.length > 20)
			lines.push(`- \`${l.locale}\` …and ${l.errors.length - 20} more`);
	}
	lines.push("", "</details>");
}
lines.push(
	"",
	"<sub>Generated by [Rosetta](https://github.com/ian/rosetta) — `rosetta push`.</sub>",
);
process.stdout.write(`${lines.join("\n")}\n`);
