// next-intl request config: load the catalogs Rosetta generates. No LLM call
// happens at request time. Translations are pre-generated by `rosetta push`.
import { getRequestConfig } from "next-intl/server";

export const locales = ["en", "es", "ja"] as const;

export default getRequestConfig(async ({ requestLocale }) => {
	const requested = await requestLocale;
	const locale = locales.includes(requested as (typeof locales)[number]) ? requested! : "en";
	return {
		locale,
		messages: (await import(`../messages/${locale}.json`)).default,
	};
});
